name: LCVFlutterSDK
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.6.0
  get_it: ^9.0.5
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.0.2
  pretty_dio_logger: ^1.4.0
  flutter:
    sdk: flutter
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^3.1.0
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/mocks/vehicle_door.json
    - assets/mocks/vehicle_info.json
  uses-material-design: true
